steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy',
         '${_FUNCTION_NAME}',
         '--source',
         'https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}',
         '--trigger-http',
         '--memory',
         '${_FUNCTION_MEMORY}',
         '--entry-point',
         'entry',
         '--runtime',
         '${_FUNCTION_RUNTIME}',
         '--region',
         '${_FUNCTION_REGION}',
         '--runtime',
         'nodejs8'
         ]

substitutions:
  _FUNCTION_NAME: reporter-websub-callback
  _FUNCTION_MEMORY: 256MB
  _FUNCTION_REGION: europe-west1
  _FUNCTION_RUNTIME: nodejs8
images: []
